name: Production

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create artifact for child wp theme
        run: |
          ls
          rm README.md
          ls
          cd wp-content/themes/btroofing-child/
          ls
          echo '>>>> remove stuff'
          echo '>>>> AFTER REMOVE stuff'                                            
          ls
          echo '>>>> BACK UP TO ROOT' 
          cd ../../../
          rm .gitignore
          rm -rf .git
          rm -rf .github
          echo '>>>> PATH AND FILES LEFT' 
          pwd
          ls

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-folder
          path: |
            *

  deployment:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    concurrency: production
    steps:
      - name: 🚚 Get latest code
        uses: actions/download-artifact@v2
        with:
          name: build-folder

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: ftps8.uk.cloudlogin.co
          username: ${{ secrets.FTP_USER_PROD }}
          password: ${{ secrets.FTP_PWD_PROD }}
